/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fantow_JNI_07b80_05355_04f7f_07528_JNITest */

#ifndef _Included_com_fantow_JNI_07b80_05355_04f7f_07528_JNITest
#define _Included_com_fantow_JNI_07b80_05355_04f7f_07528_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fantow_JNI_07b80_05355_04f7f_07528_JNITest
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fantow_JNI_07b80_05355_04f7f_07528_JNITest_sayHello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
